name: UI Test

on:
  push:
    branches: ["main"]

jobs:
  ui-test:
    runs-on: ubuntu-latest
    container:
      image: atgo/test:8.8.0

    env:
      ATGO_LICENSE: ${{ secrets.ATGO_LICENSE }}

    steps:
      - name: Checkout demo site
        uses: actions/Checkout@v4

      - name: Start virtual display
        run: |
          Xvfb :99 -ac -screen 0 1280x720x16 -nolisten tcp &
          echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Create license file
        run: |
          echo "${ATGO_LICENSE"} > /tmp/license.txt

      - name: Run ATgo
        run: | 
          cd /opt/atgo
          sed -i 's/\r$//' ATgoCUI.sh

          ./ATgoCUI.sh \
            --project="${GITHUB_WORKSPACE}/atgo_sample" \
            --run="test1.scenario" \
            --doInspection=true \
            --license="/tmp/license.txt" \
            --ignoreComparisonError=true

      - name: Upload test result
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-result
          path: atgo_sample/output